### ISSUE TITLE
Create executable with Mojo on Windows

### ISSUE THREAD

**Issue by TakamotoAI** [rschupp/PAR-Packer#47] opened 2021-06-18 07:49 UTC
I am trying to use pp to create an executable of an application that needs Mojo on Windows 10, but the exe fails with the following error:

Unable to open html entities file (C:\Users\de\AppData\Local\Temp\par-6663\cache-9973dd41d00e8bee27c9630746780ae38da71709\inc\lib\Mojo\resources\html_entities.txt): No such file or directory at C:\Users\de\AppData\Local\Temp\par-6663\cache-9973dd41d00e8bee27c9630746780ae38da71709\inc\lib/Mojo/Base.pm line 14.

The following command does not help:

-a "C:\Strawberry\perl\vendor\lib\Mojo\resources;Mojo/resources"

If I open the package once the software has run once, there is no folder "resources" in Mojo
(cross-posted in https://www.perlmonks.org/?node_id=11133963)

**Comment by rschupp** [comment] 2021-06-18 08:08
Duplicate of #44. Can you try with the fix given there (rebuild `Module::ScanDeps` from GitHub HEAD)?

**Comment by TakamotoAI** [comment] 2021-06-18 10:12
After inspecting the temp package created when the exe is launched, I was able to fix it changing

-a "C:\Strawberry\perl\vendor\lib\Mojo\resources;Mojo/resources"

to 

-a "C:\Strawberry\perl\vendor\lib\Mojo\resources;lib/Mojo/resources"

**Closed** 2021-08-16 07:45 UTC
